server:
  port: 80

spring:
 application:
  name: cloud-openfeign-order-service




 #eureka客户端配置
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka   #集群版

#设置openfeign客户端超时时间（openfeign默认是支持Ribbon的。是基于Ribbon进行的封装。可以在openfeign的包中找到Ribbon的包）
ribbon:
  ReadTimeout:  5000    #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000   #指的是建立连接后从服务器读取到可用资源所用的时间

logging:
  level:
    com.cz.springcloud.service.OpenFeignService: debug   #openfeign日志以什么级别监控哪一个接口，debug前面写的是具体接口的全路径